### ISSUE TITLE
Can't open lib FreeTDS in virtual environment

### ISSUE THREAD

**Issue by aginpatrick** [lionheart/django-pyodbc#126] opened 2016-10-31 17:39 UTC
Hi,
I'm using Django==1.6.5 and django_pyodbc==0.2.6. Everything is fine at system level. Now I created a virtual environment with these same versions and when I try to access SQL Server database, I have the following error:

'01000', "[01000] [unixODBC][Driver Manager]Can't open lib 'FreeTDS' : file not found (0) (SQLDriverConnect)"

How come is it possible since the FreeTDS .so binary lives at the system level, outside of my virtualenv?
Thanks a lot
Patrick

**Comment by aginpatrick** [comment] 2016-10-31 17:41
Forgot to mention that running manage.py runserver  --traceback does not return any error.

**Comment by RossRogers** [comment] 2016-10-31 17:49
Hello aginpatrick,

The message is _from_ unixODBC, which is actually an external C library.  That library is trying to load the FreeTDS library, but can't find it.  Thus, deep in the bowels of C, you're not going to get nice tracebacks.

Virtualenv is not a full container -- it just wraps the python libraries.  If a python library has an external, system dependency, then virtualenv doesn't actually manage that.  If you need a fully containerized instance you might need a new machine, or a new virtual machine, or possibly do some very custom chroot jailing.

To resolve the FreeTDS dependency on ubuntu, install the library with:

    sudo apt-get install freetds-dev 

You'll still have to configure your other freetds and unixodbc library config files which are at:
    /etc/odbcinst.ini
    /etc/odbc.ini /etc/
    /etc/freetds/freetds.conf


Closing as not a bug, but feel free to comment more or reopen if you have more evidence that this is still a django-pyodbc issue.

**Closed by RossRogers** 2016-10-31 17:49 UTC

**Comment by aginpatrick** [comment] 2016-10-31 18:38
Thanks Ross for your answer and sorry if I thought that it is a problem with django-pyodbc. On the other way, I don't see why it does work outside the virtualenv (where the FreeTDS library is already installed and  unixodbc library config files already configured) and not in my virtualenv. I tried to google the problem but no success yet.

**Comment by RossRogers** [comment] 2016-10-31 18:48
No prob.  I've had my head bitten off by the neckbeards for filing a bad bug before.

`LD_LIBRARY_PATH` is the path that is searched when loading a C/C++ library.  Outside your virtualenv, do:

    echo $LD_LIBRARY_PATH

One of those directories has a file called `libFreeTDS.so`.  Inside your virtual env, assuming you're using Bash, do:

    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/the/magical/path"
   
Then try running django again.  If it works, you need to put `/the/magical/path` at the end of `LD_LIBRARY_PATH` in virtualenv somehow.  I'm not sure how to do that, but I'm sure a quick google of setting environment variables should solve the problem.

**Comment by aginpatrick** [comment] 2016-10-31 19:12
Unfortunately it does not work. Actually my $LD_LIBRARY_PATH variable is empty outside my virtual environment but even if set it with the correct path in my virtual env (with the libraries I found for freetds, that is /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so and /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so - there is no such a file as libFreeTDS.so on my system), it raises the same error.

**Comment by aginpatrick** [comment] 2016-10-31 19:24
When I diff the two pyodbc.so that I have (one in /usr/local/lib/python2.7/dist-packages/ and the other in my virtual environment ./venv/lib/python2.7/site-packages), I noticed that the 2 files differ. I copied the first one in my venv/../site-packages directory and it works now. I don't know why the 2 libraries are different since the django_pyodbc modules have the same version. Maybe because when I installed the module for the first time long time ago, I install pyodbc first and then django_pyodbc ? (I noticed that the install of django_pyodbc in my venv installs also the pyodbc.so)

**Comment by RossRogers** [comment] 2016-10-31 19:34
Yeah, pyodbc is a separate package that django-pyodbc depends on.    What does `ldd` of those two versions of `pyodbc.so` show you?

**Comment by RossRogers** [comment] 2016-10-31 19:36
Also, I was a liar.  I thought that `FreeTDS` message was a linker error.  Apologies.

**Comment by aginpatrick** [comment] 2016-11-01 13:40
Hi Ross, here is the result of the diff between the two pyodbc.so files (first one in diff is the one that works):

2c2
< 	libodbc.so.1 => /usr/lib/x86_64-linux-gnu/libodbc.so.1 ()
---
> 	libodbc.so.2 => /usr/local/lib/libodbc.so.2 ()
7d6
< 	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 ()

**Comment by RossRogers** [comment] 2016-11-01 14:57
You're frozen on django_pyodbc==0.2.6,  it looks like you'll need to freeze
on an earlier pyodbc too.  If you do `pip freeze | grep pyodbc` outside
your virtual env, that will tell you the new pyodbc version.

However, have you tried upgrading to the latest django_pyodbc and pyodbc?
Maybe that'll work

**Comment by aginpatrick** [comment] 2016-11-03 02:14
Unfortunately not. Same error on my system in a virtual environment with django_pyodbc==0.4.4. and pyodbc==3.0.10. On the other hand, same install in a virtual environment on a fresh new instance (Ubuntu instance on AWS) is working. I suspect that something happened when I installed couple of years ago packages like unixodbc-dev, freetds-dev, tdsodbc, etc.
