### ISSUE TITLE
SchemaEditor error

### ISSUE THREAD

**Issue by thomgonzalez** [lionheart/django-pyodbc#150] opened 2017-06-16 05:07 UTC
I have problems in database migration, as I can solve this error.
I requirements:
Python 3.5
Django 1.8
Pyodbc 3.0.7
django-pyodbc 1.1.0

Error:
'The SchemaEditorClass attribute of this database wrapper is still None')
NotImplementedError: The SchemaEditorClass attribute of this database wrapper is still None

**Comment by timgraham** [comment] 2017-08-24 18:54
Duplicate of https://github.com/lionheart/django-pyodbc/issues/110.

**Closed** 2017-12-13 14:28 UTC
Labels: duplicate
