### ISSUE TITLE
Sybase issue

### ISSUE THREAD

**Issue by JonahJ** [lionheart/django-pyodbc#103] opened 2015-10-14 14:00 UTC
Getting the following error from this module. I'm using Sybase IQ 15. Anyone have any suggestions? Sybase IQ instead supports `sa_eng_properties` which yields such properties. Also hope Python3 support is in the works!

```
    cursor = self.make_debug_cursor(self._cursor())
  File "C:\Python27\lib\site-packages\django_pyodbc-0.3.0-py2.7.egg\django_pyodbc\base.py", line 308, in _cursor
    if self.ops.sql_server_ver < 2005:
  File "C:\Python27\lib\site-packages\django_pyodbc-0.3.0-py2.7.egg\django_pyodbc\operations.py", line 69, in _get_sql_server_ver
    cur.execute("SELECT CAST(SERVERPROPERTY('ProductVersion') as varchar)")
  File "C:\Python27\lib\site-packages\django\db\backends\util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python27\lib\site-packages\django_pyodbc-0.3.0-py2.7.egg\django_pyodbc\base.py", line 440, in execute
    raise utils.DatabaseError(*e.args)
DatabaseError: ('42S02', "[42S02] [Sybase][ODBC Driver][Sybase IQ]Procedure 'SERVERPROPERTY' not found (-265) (SQLExecDirectW)")
```

**Comment by RossRogers** [comment] 2015-10-14 15:46
JonahJ,

Do you know if there are free/trial/express versions of Sybase?  I want to get or cross-platform/ multi-version testing up to snuff, but since I don't have Sybase, I can't reproduce your issues at the moment.

**Comment by JonahJ** [comment] 2015-10-14 19:17
@RossRogers Unfortunately I do not believe so. Really only enterprise uses. Although I can connect fine through pyodbc manually?

**Comment by RossRogers** [comment] 2015-10-14 20:20
Heheh.  Well, I guess you're on your own!

Around line 69 of base.py, where the raw SQL token `SERVERPROPERTY` is injected, there is code that handles other databases.  I had to monkey with that code when I ported django pyodbc to work with IBM's DB2 between these commits:

    git diff 8c3f918 ad98476c

**Comment by RossRogers** [comment] 2016-11-08 03:13
Closing due to lack of volunteers.

**Closed by RossRogers** 2016-11-08 03:13 UTC
