### ISSUE TITLE
Error: SchemaEditorClass

### ISSUE THREAD

**Issue by anishukserg** [lionheart/django-pyodbc#164] opened 2018-06-13 07:33 UTC
HI! I Create new project with django-2.0.6 and django-pyodbc-2.0.0a1.

When run puthon manage.py migrate I recive error

File "/home/xxx/yyy/env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 616, in schema_editor

    'The SchemaEditorClass attribute of this database wrapper is still None')

**Comment by RossRogers** [comment] 2018-06-18 15:39
Unfortunately, this is a duplicate of a [longstanding bug](https://github.com/lionheart/django-pyodbc/issues/47)

**Closed** 2018-06-18 15:38 UTC
