### ISSUE TITLE
Django 1.7 compatibilty

### ISSUE THREAD

**Issue by jieter** [lionheart/django-pyodbc#52] opened 2014-04-18 11:09 UTC
#51 was my naive attempt to use django-pyodbc with 1.7b1, it seems to be more complicated...

This is what I've found so far:
1. A `ProgrammingError: Attempt to use a closed cursor` is raised on select queries.[commit comment](https://github.com/django/django/commit/0837eacc4e1fa7916e48135e8ba43f54a7a64997#commitcomment-6053889)
   If I replace `cursor.close()` with `pass` on django/db/models/sql/compiler.sql:820, selecting stuff in the shell works again. But it obviously needs to be fixed at `django-pyodbc`s side.
2. The use of `TEST_*` prefixes in the `DATABASES` setting is deprecated, but `django-pyodbc` assumes the keys exist. This makes test database creation fail.
3. Schema editors. Django 1.7 ships with migrations, so the `BaseDatabaseWrapper` defines a method `schema_editor` which raises `NotImplementedError`.
   
   ```
   ...
   File "/home/jieter/.virtualenvs/pyodbc-test/local/lib/python2.7/site-packages/django/db/backends/__init__.py", line 546, in schema_editor
   raise NotImplementedError('subclasses of BaseDatabaseWrapper may require a schema_editor() method')
   NotImplementedError: subclasses of BaseDatabaseWrapper may require a schema_editor() method
   ```
   
   If I add a method returning a simple SchemaEditor like this:
   
   ``` python
   def schema_editor(self, *args, **kwargs):
       "Returns a new instance of this backend's SchemaEditor"
       return DatabaseSchemaEditor(self, *args, **kwargs)
   ```
   
   (together with a `DatabaseSchemaEditor` extending `BaseDatabaseSchemaEditor`), I get a `TransactionManagementError` when `./manage.py runserver`:
   
   ```
   ...
   File "/home/jieter/.virtualenvs/pyodbc-test/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 148, in build_graph
     self.applied_migrations = recorder.applied_migrations()
   File "/home/jieter/.virtualenvs/pyodbc-test/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 48, in applied_migrations
     self.ensure_schema()
   File "/home/jieter/.virtualenvs/pyodbc-test/local/lib/python2.7/site-packages/django/db/migrations/recorder.py", line 41, in ensure_schema
     with self.connection.schema_editor() as editor:
   File "/home/jieter/.virtualenvs/pyodbc-test/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 74, in __enter__
     atomic(self.connection.alias, self.connection.features.can_rollback_ddl).__enter__()
   File "/home/jieter/.virtualenvs/pyodbc-test/local/lib/python2.7/site-packages/django/db/transaction.py", line 274, in __enter__
     "The outermost 'atomic' block cannot use "
   django.db.transaction.TransactionManagementError: The outermost 'atomic' block cannot use savepoint = False when autocommit is off.
   ```

idea's?

**Comment by tsobeng** [comment] 2015-02-10 16:29
Hi all, 

I have the same error,

I use django1.7 and pyobdc on windows 7

when I try to connected to an MS Access DB, I have this error

raise NotImplementedError('subclasses of BaseDatabaseWrapper may require a schema_editor() method')
NotImplementedError: subclasses of BaseDatabaseWrapper may require a schema_editor() method

Thanks

**Comment by deumo** [comment] 2015-02-10 16:36
I just got the same error on Windows 7. Which django version can correct this or which patch should I apply whith Django 1.7 ?
I use pyodbc 3.0.7.

Thanks.

**Comment by tax** [comment] 2015-02-10 16:50
Django 1.7 is not yet supported so you might try using django 1.6

**Comment by GordonFreemem** [comment] 2015-02-10 16:54
I switched to django-pyodbc-azure. Works perfect with Django 1.7 and MS SQL-Server.

**Comment by gereltod-g** [comment] 2015-02-13 03:12
same problem here. django 1.7

**Comment by deumo** [comment] 2015-02-16 07:23
thank you for your reply.

2015-02-10 17:54 GMT+01:00 Gordon Schultz <notifications@github.com>:

**Comment by RossRogers** [comment] 2015-03-16 22:34
For "Issue 1" - `A ProgrammingError: Attempt to use a closed cursor`, I believe this is just a behavior difference between `pyodbc` and other database backends.  If you look at [the Django trunk](https://github.com/django/django/blob/f269c1d6f6dcc22c0a781f3223c6da0a4483b06e/django/db/models/sql/compiler.py#L849) for file `django/db/models/sql/compiler.py`, it has these two snippets:   

    849 result = cursor_iter(
    850     cursor, self.connection.features.empty_fetchmany_value,
    851     self.col_count
    852 )
    853 if not self.connection.features.can_use_chunked_reads:
    854     try:
    855         # If we are using non-chunked reads, we return the same data
    856         # structure as normally, but ensure it is all read into memory
    857         # before going any further.
    858         return list(result)
    859     finally:
    860         # done with the cursor
    861         cursor.close()

and the [`cursor_iter()` definition](https://github.com/django/django/blob/f269c1d6f6dcc22c0a781f3223c6da0a4483b06e/django/db/models/sql/compiler.py#L1129) :

    1129 def cursor_iter(cursor, sentinel, col_count):
            [...]
    1134     try:
    1135         for rows in iter((lambda: cursor.fetchmany(GET_ITERATOR_CHUNK_SIZE)),
    1136                          sentinel):
    1137             yield [r[0:col_count] for r in rows]
    1138     finally:
    1139         cursor.close()

849 creates an iterator with a built-in `close()` function.  858 invokes the iterator to completion, calling that `close()` function, and 861 invokes the `close()` function a 2nd time.

So I think the solution might be to wrapper the `cursor`'s `close()` function to silence the `ProgrammingError` exceptions resulting from closing a pyodbc cursor more than once:

    diff --git a/django_pyodbc/base.py b/django_pyodbc/base.py
    index 747f36e..47099ae 100644
    --- a/django_pyodbc/base.py
    +++ b/django_pyodbc/base.py
    @@ -367,6 +367,12 @@ class CursorWrapper(object):
             self.last_params = ()
             self.encoding = encoding
     
    +    def close(self):
    +        try:
    +            self.cursor.close()
    +        except Database.ProgrammingError:
    +            pass
    +
         def format_sql(self, sql, n_params=None):
             if not self.driver_supports_utf8 and isinstance(sql, text_type):
                 # Older FreeTDS (and other ODBC drivers?) don't support Unicode yet, so

Let me know if this is the correct path and whether I should create a pull request for it.

**Comment by dlo** [comment] 2015-03-16 22:38
@RossRogers this looks like a solid path to pursue. :+1: on a PR.

**Comment by RossRogers** [comment] 2015-03-16 22:42
#78

**Comment by steve17767** [comment] 2016-01-07 19:19
I don't understand if this problem was solved or not.  

I'm upgrading from Djano 1.6 to 1.7.
Python 2.7.6.
pyodbc 3.0.7
django_pyodbc 0.2.5
Ubuntu 12.04

Everything went as planned except for accessing remote database tables (MySQL and Ms-SQL Server).  All of the tables are configured "managed-false".  When I try to access the table I get:

    RuntimeError: Conflicting 'bugview_deferred_description_disposition_divisioaf59cb28117de5eb6ddfea0476dab601' models in application 'nvbugsdw': <class 'bug_metrics.models_bugs.BugView_Deferred_Description_Disposition_Divisioaf59cb28117de5eb6ddfea0476dab601'> and <class 'bug_metrics.models_bugs.BugView_Deferred_Description_Disposition_Divisioaf59cb28117de5eb6ddfea0476dab601'>

To fix address that I was instructed to makemigrations on the remote (not managed by Django) DB (see http://stackoverflow.com/questions/34620588/conflicting-models-in-application-with-external-database-tables).  So I tried and got:

    NotImplementedError: subclasses of BaseDatabaseWrapper may require a schema_editor() method

Any suggestions?  I've been stuck for a couple of days. 

Thanks in advance for any help.

**Comment by RossRogers** [comment] 2016-01-07 19:59
It looks like this class is somehow getting included twice:

    bug_metrics.models_bugs.BugView_Deferred_Description_Disposition_Divisioaf59cb28117de5eb6ddfea0476dab601

Do you have the bug_metrics "app" installed twice?

**Comment by steve17767** [comment] 2016-01-07 20:10
No.  Problem appeared when I upgrade from 1.6 to 1.7.  It happens only on tables that are defined on remote MS-SQL Servers.  The model.py file containing the definition is incldued in multiple other files (views, commands, etc.) but the application is only loaded once.

I have 11 apps.  2 access remote DBs the other 9 access local MySQL DB tables.  Only the two apps that access the remote DB display this problem.

**Comment by RossRogers** [comment] 2016-01-07 20:53
So, the table `BugView_Deferred_Description_Disposition_Divisioaf59cb28117de5eb6ddfea0476dab601` has Meta field `managed=False` like?

    class Meta:
        managed = False

Did it transition from managed to un-managed? 

I've seen the Django migration system get screwed up before.  If you don't think you'll need to rollback any migrations ( you can always create a forward migration at a later date that undoes the edits), then I would try:

* Nuking all files in the `bug_metrics/migrations` directory
* Nuke all rows in table `django_migrations`
* Recreate an initial migration with:

        python manage.py makemigrations bug_metrics
* Then fake out the migration, as it is already in a known state:
        
        python manage.py migrate --fake bug_metrics

**Comment by RossRogers** [comment] 2016-01-07 21:13
One more thought: If you want to root cause this, I'd launch a debugger like [winpdb](http://winpdb.org/):

Then put this line:

    import rpdb2; rpdb2.start_embedded_debugger('foo')

 in file `django/apps/registry.py` right before the RuntimeError is thrown:

    raise RuntimeError(
                    "Conflicting '%s' models in application '%s': %s and %s." %
                    (model_name, app_label, app_models[model_name], model))

Then:
* run your command that throws the error
* wait for it to hang ( right before that error)
* launch winpdb GUI 
* File->Attach, password 'foo'
* Click up the stack and see how it got to that error.

**Comment by steve17767** [comment] 2016-01-07 21:15
Don't know if this makes any difference or not:

The application bug_metrics has 3 models*.py files.  Two of them define local database tables.  The third one defines classes for managed = False tables that were created by hand (may have used inspectdb tool).  So the bug_metrics applicaiton has a mix of tables.

I migrated bug_metrics (cleared out the migrations directory of everything but __init__.py, ran makemiragtion and migrate) that created the FAKE migrations.

The "bugview" table ("bug_metrics.models_bugs.BugView_...") has always been manged = False.

    class BugView(models.Model):
        BugId            = models.BigIntegerField(primary_key=True)
        Module           = models.CharField(max_length=128, null=False)
        Severity         = models.CharField(max_length=50, null=False)
        Disposition      = models.CharField(max_length=64, null=False)
        Division         = models.CharField(max_length=64, null=False)
    . . .
    class Meta:
        app_label = 'nvbugsdw'
        managed   = False
        db_table  = 'bugview'

**Comment by steve17767** [comment] 2016-01-07 21:16
Ok.  And I'll try the debugger approach too.

**Comment by RossRogers** [comment] 2016-01-07 21:21
Is that `app_label= 'nvbugsdw'` necessary?  If you nuke that line, does this issue disappear?

**Comment by steve17767** [comment] 2016-01-07 21:32
Same issue with or without it.

**Comment by RossRogers** [comment] 2016-01-07 21:34
Interesting.  I'd definitely go the debugger route then.  If you haven't done that before, it is _extremely_ powerful when root-causing issues.

**Comment by steve17767** [comment] 2016-01-07 21:35
I did notice one other oddity.  When I run

    ./manage.py runserver --nothreading 0.0.0.0:8081

With print statements in manage.py, manage.py seems to be run twice.  Is that expected?

**Comment by RossRogers** [comment] 2016-01-07 21:38
manage.py will reload everything anytime a file in any loaded apps is changed.

**Comment by steve17767** [comment] 2016-01-07 22:28
Thanks for the debug tip.  Found this:


In my view I define:
    context_object_name = 'open_bugs'
    model = BugView

I override get_queryset() to retrieve the list of record I want:
        bv = BugView()
        sql = bv.get_open_bugs_for_user_sql(self.filter_username)
        bugs = BugView.objects.raw(sql)

I then iterate over the list to cont certain states, etc.
    for bug in bugs:
        if bug.State == ...

I pass the "bugs" results to context:

    get_context_data(self, **kwargs):
        context = super(UserBugsView, self).get_context_data(**kwargs)

Then  in the template I iterate over the passed in "open_bugs" (which I have already iterated over once):

    {% for bug in open_bugs %}
    <tr>
    <td><a href="http://nvbugs/{{ bug.BugId }}" target="_blank">{{ bug.BugId }}</a> &nbsp;&nbsp;</td>
    ...

Looking at dist-packages/django/apps/registry.py, line 210-ish

    def register_model(self, app_label, model):
        # Since this method is called when models are imported, it cannot
        # perform imports because of the risk of import loops. It mustn't
        # call get_app_config().
        model_name = model._meta.model_name
        app_models = self.all_models[app_label]
        print "-----> app_label  = "+app_label
        print "-- --> model_name = "+model_name
        print "- - -> app_models = "+str(app_models)
        if model_name in app_models:
            raise RuntimeError(
                "Conflicting '%s' models in application '%s': %s and %s." %
                (model_name, app_label, app_models[model_name], model))

(I added the print lines)

When the views code counts the bugs I see in the trace:

    -----> app_label  = nvbugsdw
    -- --> model_name = bugview_deferred_description_disposition_divisioaf59cb28117de5eb6ddfea0476dab601
    - - -> app_models = OrderedDict([('bugview', <class 'bug_metrics.models_bugs.BugView'>)])

and then when the open_bugs gets to the template I see in the trace:

    -----> app_label  = nvbugsdw
    -- --> model_name = bugview_deferred_description_disposition_divisioaf59cb28117de5eb6ddfea0476dab601
    - - -> app_models = OrderedDict([('bugview', <class 'bug_metrics.models_bugs.BugView'>), ('bugview_deferred_description_disposition_divisioaf59cb28117de5eb6ddfea0476dab601', <class 'bug_metrics.models_bugs.BugView_Deferred_Description_Disposition_Divisioaf59cb28117de5eb6ddfea0476dab601'>)])

which raises the error.

This is the same code I ran under 1.5 and 1.6 Django.

Thoughts?

**Comment by RossRogers** [comment] 2016-01-07 22:37
That code you just pasted is not the latest 1.7 minor release number.  `sudo pip install django 1.7.11`.  If you do `pip install 1.7` it literally installs 1.7, not the highest minor number.  To find the versions, do : 

    pip install yolk # might need sudo pip ...
    yolk -V django

The latest 1.7 minor/bug release number is 1.7.11.

**Comment by steve17767** [comment] 2016-01-07 22:44
UNBELIEVABLE!!!!  I'm such an idiot.

Thank you so much for noticing that.  It works now.

**Comment by RossRogers** [comment] 2016-01-07 22:47
That has bit me before too.  I think `pip install django==1.7` should pick the highest bug release as well.  Oh well.  

Yay team.

**Comment by steve17767** [comment] 2016-01-07 23:01
Yes, I just assumed it would.  Didn't some general say something about assumption is the mother of all ..."

Again, thanks.

**Comment by RossRogers** [comment] 2016-11-08 03:03
I believe we have _generic_ 1.7 support on the trunk as I am using it (shame on me).  For specific 1.7 bugs, please file a new ticket.

**Closed by RossRogers** 2016-11-08 03:03 UTC
Labels: enhancement

**Comment by connorbode** [comment] 2016-11-23 04:16
@RossRogers nope, just tried with 1.7 and ran into the exact same errors commented at the beginning of this thread (dating from 2014)

**Comment by RossRogers** [comment] 2016-11-23 15:15
Connor,

Did you run against `1.7` or the patched up version `1.7.11`?  What does `pip freeze | egrep '(django|odbc)'` give you?

**Comment by RossRogers** [comment] 2016-11-23 15:24
If you can make an [S.S.C.C.E](http://sscce.org/) and indicate which specific issue of the 4 listed in the first post is still surfacing, that would be helpful.

**Comment by connorbode** [comment] 2016-11-24 15:49
@RossRogers Looking back on this now, my issues are all related to migrations and the lack of a `SchemaEditorClass`.  After searching through the repo, I'm assuming migrations are not supported.

`inspectdb` worked for me (so far, I haven't actually tried retrievals yet).
